exit status: 0
stdout:
let f1 : Int -> Int -> Int =
    fun (x : Int) (y : Int) => let a : (Int, Int) = (x, y);
    match a._0 {
        0 => let a : Int = a._1;
        a,
        1 => match a._1 {
            0 => let b : Int = a._0;
            b,
            1 => let c : Int = a._1;
            c,
            _ => let c : Int = a._1;
            c,
        },
        _ => match a._1 {
            0 => let b : Int = a._0;
            b,
            1 => let d : Int = a._0;
            d,
            _ => 5,
        },
    };
let f2 : Int -> Int -> Int =
    fun (x : Int) (y : Int) => let p : (Int, Int) = (x, y);
    match p._0 {
        0 => let a : Int = p._1;
        a,
        1 => match p._1 {
            0 => let b : Int = p._0;
            b,
            1 => let c : Int = p._1;
            c,
            _ => let c : Int = p._1;
            c,
        },
        _ => match p._1 {
            0 => let b : Int = p._0;
            b,
            1 => let d : Int = p._0;
            d,
            _ => 5,
        },
    };
() : ()

stderr:
